### ISSUE TITLE
can hasFlowFinishedSuccessfully return false?

### ISSUE THREAD

**Issue by kelvinaliyanto** [MinaSamir11/react-native-in-app-review#104]
Is there any scenario where hasFlowFinishedSuccessfully return false? There is nothing mentioned in the documentation of getting false for hasFlowFinishedSuccessfully. I tried searching for the info in the repo's issue, but there isn't clear answer.

**Comment by rabihiawaludin** [comment]
Up, answer this question please...

**Comment by MinaSamir11** [comment]
it may return false from android review flow, which API is responsible for that response, otherwise it return true alway in iOS.
