### ISSUE TITLE
Rating popup is not showing

### ISSUE THREAD

**Issue by aparnagude** [MinaSamir11/react-native-in-app-review#11]
After installed this library 2 times the popup is displayed. But after that popup is not displaying. Can u help me to fix this issue. May I know the limit of this api and how to increase the limit

**Comment by iamNarcisse** [comment]
@aparnagude, one cannot increase the limit of the number of times the popup shows. It's controlled automatically by google play. For more info visit https://developer.android.com/guide/playcore/in-app-review

**Comment by MinaSamir11** [comment]
@aparnagude  hello, 
as, @iamNarcisse  said you cannot increase limit, of calling inAppReview. As app store and playstore, set limitations on calling method in your app, and user that has submit review. 🌹
