### ISSUE TITLE
Cannot submit rating in dev mode to test, "Submit" button greyed out

### ISSUE THREAD

**Issue by newtracs** [MinaSamir11/react-native-in-app-review#120]
I'm able to get the review prompt to display, however I cannot press submit in Release mode (when installing Release on my iOS device from Xcode).

Do I need to publish to App Store to test the full flow (Prompt appears > select stars > press Submit)?

**Comment by MinaSamir11** [comment]
Yes, you have to upload the new version to the store. 
#[Check_READme](https://github.com/MinaSamir11/react-native-in-app-review#please-note-to-test-your-integration-using-the-app-store
).

**Comment by newtracs** [comment]
Thanks - from what I gather from the Readme, are we only able to test functionality using Jest?

**Comment by MinaSamir11** [comment]
Yes you can test if function triggered or not, 
check example test : 
 
https://github.com/MinaSamir11/react-native-in-app-review/blob/master/Example/__tests__/useAppReview-test.js

**Comment by newtracs** [comment]
Thanks for this.  So we aren't able to test functionality without Jest?

**Comment by vektorat-manish948** [comment]
Hello @MinaSamir11 ,

I have the same issue which is mentioned in this main thread but along with that i want to know,
Where do i mention apple app id in code  to send my review and rating to apple app store ?
Or we don't need to mention the app id in code ?

Please let me know.
Thank you in advance.

**Comment by MinaSamir11** [comment]
> Thanks for this. So we aren't able to test functionality without Jest?

Sorry for the late, you can prompt the UI in dev and production mode, you can't test trigger the UI in testflight mode. 
Thank you

**Comment by MinaSamir11** [comment]
> Hello @MinaSamir11 ,
> 
> I have the same issue which is mentioned in this main thread but along with that i want to know, Where do i mention apple app id in code to send my review and rating to apple app store ? Or we don't need to mention the app id in code ?
> 
> Please let me know. Thank you in advance.

You don't need that once you submit the review request goes through API that is implemented natively.

**Comment by vektorat-manish948** [comment]
> > Hello @MinaSamir11 ,
> > I have the same issue which is mentioned in this main thread but along with that i want to know, Where do i mention apple app id in code to send my review and rating to apple app store ? Or we don't need to mention the app id in code ?
> > Please let me know. Thank you in advance.
> 
> You don't need that once you submit the review request goes through API that is implemented natively.

Thank you very much for your valuable response. You saved my day

**Comment by thatgriffith** [comment]
Looks like this is not an issue any longer and should be resolved/closed?

**Comment by MinaSamir11** [comment]
> closed

resolved

**Comment by parag-mer** [comment]
hello can anyone guide how to test it in ios, because i am getting the popup for the rating but not able to submit it ( i don't not why the submit button is disabled)

**Comment by thatgriffith** [comment]
> hello can anyone guide how to test it in ios, because i am getting the popup for the rating but not able to submit it ( i don't not why the submit button is disabled)

Please read previous posts and also see the docs [here](https://github.com/MinaSamir11/react-native-in-app-review#please-note-to-test-your-integration-using-the-app-store)
