### ISSUE TITLE
Has reviewed

### ISSUE THREAD

**Issue by AlenToma** [MinaSamir11/react-native-in-app-review#124]
Hi, thx for the library, it's really great.

I was wondering is it possible to implement if the user has a review already for the app.

This is imported becouse when doing request the app goes in the background for a moment even though the dialog dose not necceray show upp.

It will be great if there is a method that says hasAction or something like that.

Would also be happy to help if you could point me to a right direction. I could do it my self and post it here.

Becouse as I checked there no such a method in `com.google.android.play.core.review.ReviewManager`
I may be wrong though as I am not an expert in java.

**Comment by jforaker** [comment]
@AlenToma you should probably do that on the react-native side, with a simple value such as:

```js
AsyncStorage.setItem(REVIEW_DONE_KEY, 'true');
```

And then check it later:

```js
  const reviewDone = await AsyncStorage.getItem(REVIEW_DONE_KEY);
  if (reviewDone) {
    return;
  }
```
