### ISSUE TITLE
How can we change the Popup title and description?

### ISSUE THREAD

**Issue by ShashikaVirajh** [MinaSamir11/react-native-in-app-review#128]
@MinaSamir11 first of all, thanks very much for this superb library. I just want to know, is there any way that we can change the title and the description of the popup? Is it customisable?

**Comment by Yuniac** [comment]
I would like to know as well but I think it's hard coded

**Comment by MinaSamir11** [comment]
It’s implemented and designed by APIs(google) and cannot be customizable. if you find any updating in doc APIs and it can be done please mention it to me .
