### ISSUE TITLE
iOS - requestReview is deprecated

### ISSUE THREAD

**Issue by cristianoccazinsp** [MinaSamir11/react-native-in-app-review#13]
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview?language=objc

`requestReview` is deprecated in favour of `requestReviewInScene`

**Comment by StriderHND** [comment]
Any updates on this?

**Comment by MinaSamir11** [comment]
Ok, I will update it, soon as possible🌹

**Comment by vshjxyz** [comment]
Hello, is the current version (`requestReview`) still working on latest iOs versions? I'm having troubles getting the prompt shown on an iPhone 12, I wonder if this is actually a blocking issue or not (meaning that we should update to `requestReviewInScene` but `requestReview` still works for now (?))

**Comment by chrispyballer** [comment]
any update on this? requestReview seems to be not working indefinitely as of Apple's latest update (14.5.1), thus rendering this library useless for updated iOS users. 😿

**Comment by MinaSamir11** [comment]
@cristianoccazinsp @StriderHND @vshjxyz @chrispyballer 
package updated to support iOS 14+ 
v3.2.0 

Please inform me if there is any error that occurs in the new version.
