### ISSUE TITLE
Android not opening the popup. Shows: [Error: Failed to bind to the service.]

### ISSUE THREAD

**Issue by basit-rayn** [MinaSamir11/react-native-in-app-review#138]
The popup is working fine on iOS but on android, it is throwing an error [Error: Failed to bind to the service]. Not sure what exactly is the reason. I have confirmed that all the installation is fine on the android native side as well. Still, the reason is unknown. Previously it was working fine. 
The implementation is same as it is given in documentation.
This behavior is occurring on both the android emulators and physical devices.

**Comment by basit-rayn** [comment]
@snyk-bot @bytehala @TaylorDale @MetinArslanturk any idea about this issue?

**Comment by parthkanani93** [comment]
++

**Comment by 4xiom** [comment]
Any updates on this issue?

**Comment by kolindalanaresh** [comment]
@MinaSamir11  please update the build Soon

**Comment by SeongwoonHong** [comment]
@MinaSamir11  i'm seeing this issue as well. @basit-rayn  any updates?

**Comment by MinaSamir11** [comment]
Sorry for the late response.

The new release is now available, follow the new readme.md installation steps. 
https://github.com/MinaSamir11/react-native-in-app-review/releases/tag/v4.3.1

For the public registry, the new release will be available in 10 days.

**Comment by SeongwoonHong** [comment]
> 

looking forward to use the new release

**Comment by virenradadiya** [comment]
Hi there,

I'm experiencing the same issue with version "^4.2.1" of the npm library. Has anyone found a solution for this problem?

Thanks in advance for any assistance you can provide.

**Comment by chen-rn** [comment]
> Sorry for the late response.
> 
> The new release is now available, follow the new readme.md installation steps. https://github.com/MinaSamir11/react-native-in-app-review/releases/tag/v4.3.1
> 
> For the public registry, the new release will be available in 10 days.

is it available for the one in the public registry now?

**Comment by MinaSamir11** [comment]
the new public version available now 4.3.1

**Comment by Robiullah2244** [comment]
Hi @MinaSamir11, I am experiencing the same issue in 4.3.1.

**Comment by AahilShahzad** [comment]
@MinaSamir11 , same issue with 4.3.1

**Comment by AahilShahzad** [comment]
@MinaSamir11  can you please help us out v@4.3.1 not worked for android as well
