### ISSUE TITLE
App crashes if google play store is not installed

### ISSUE THREAD

**Issue by felipecespedes** [MinaSamir11/react-native-in-app-review#15]
When calling the `InAppReview.RequestInAppReview()` method then the app is crashing if the Google Play Store is not installed.

Google play store is a required dependency as listed in the [In-App Review official documentation](https://developer.android.com/guide/playcore/in-app-review#device-requirements)
> Android devices (phones and tablets) running Android 5.0 (API level 21) or higher that have the Google Play Store installed.

Platform: Android

**Comment by MinaSamir11** [comment]
If you need, quick sol. You can call method, wrapping it in try {}catch. You will silence error. 

So i will work on it to fix crashing app, If user not install dependence.

**Comment by felipecespedes** [comment]
@MinaSamir11 Since this error is at the Java level then the JS try-catch block won't help too much, I tested it and the app was still crashing.

I did a lazy patch on my own fork, it's just some try-catch blocks, I left some TODO notes on it for a more elegant solution in the future though.
https://github.com/felipecespedes/react-native-in-app-review/commit/249ecfcc21bbafed4e25591e035ce4dab25a2e39

**Comment by fevzican** [comment]
@MinaSamir11 when can you update this package for fixing this issue ?

**Comment by MinaSamir11** [comment]
> When calling the `InAppReview.RequestInAppReview()` method then the app is crashing if the Google Play Store is not installed.
> 
> Google play store is a required dependency as listed in the [In-App Review official documentation](https://developer.android.com/guide/playcore/in-app-review#device-requirements)
> 
> > Android devices (phones and tablets) running Android 5.0 (API level 21) or higher that have the Google Play Store installed.
> 
> Platform: Android

Thank you @felipecespedes , I solve bug without try{}catch{}, now we check if play store installed or not and show in app review if play store exist in user device, install new update and check it out..

**Comment by MinaSamir11** [comment]
> @MinaSamir11 when can you update this package for fixing this issue ?

update live now install new package.

**Comment by MinaSamir11** [comment]
> > @MinaSamir11 when can you update this package for fixing this issue ?
> 
> @fevzican  update live now, install new package.

**Comment by MinaSamir11** [comment]
@felipecespedes  @fevzican   i apologize for the pervious version of 2.1.3, i found that is not solved yet. i update package to 2.1.4 for your issue. please notify me if it works or not ! 
Thank you.

**Comment by mToutounjy** [comment]
@MinaSamir11  i have tested V2.1.4 and the problem still exist. Also if the Play Store app was disabled the app will crash too

**Comment by felipe-cespedes** [comment]
What Android version/API were you testing on? @mToutounjy

**Comment by felipecespedes** [comment]
What Android version/API were you testing on? @mToutounjy

**Comment by mToutounjy** [comment]
@felipecespedes Android 8.1.0 API 26

**Comment by MinaSamir11** [comment]
@felipecespedes Is problem solved for you after update to 2.1.4!! Or still exist!?

**Comment by MinaSamir11** [comment]
> @MinaSamir11  i have tested V2.1.4 and the problem still exist. Also if the Play Store app was disabled the app will crash too

If disable, it may crash too. We can resolve it, in next release.
But If playstore is not installed, crash with you too!!

**Comment by mToutounjy** [comment]
> > @MinaSamir11  i have tested V2.1.4 and the problem still exist. Also if the Play Store app was disabled the app will crash too
> 
> If disable, it may crash too. We can resolve it, in next release.
> But If playstore is not installed, crash with you too!!

yes,i t's crash if play store is not installed. 


I/ReactNativeJS: RequestInAppReview
I/PlayCore: UID: [10082]  PID: [27654] ReviewService : requestInAppReview (xxx.xxx.xxx)
I/PlayCore: UID: [10082]  PID: [27654] ReviewService : Initiate binding to the service.
I/PlayCore: UID: [10082]  PID: [27654] ReviewService : Failed to bind to the service.
E/isPlayStoreInstalled: true
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx.xxx.xxx, PID: 27654
    com.google.android.play.core.tasks.RuntimeExecutionException: com.google.android.play.core.internal.aq: Failed to bind to the service.
        at com.google.android.play.core.tasks.m.getResult(Unknown Source:16)
        at com.ibits.react_native_in_app_review.AppReviewModule.lambda$show$1$AppReviewModule(AppReviewModule.java:53)
        at com.ibits.react_native_in_app_review.-$$Lambda$AppReviewModule$bUmS5pB5E-8STvn0S-VVfLR6ozE.onComplete(Unknown Source:4)
        at com.google.android.play.core.tasks.a.run(Unknown Source:23)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.google.android.play.core.internal.aq: Failed to bind to the service.
        at com.google.android.play.core.internal.ap.a(Unknown Source:78)
        at com.google.android.play.core.internal.ai.a(Unknown Source:4)
        at com.google.android.play.core.internal.ag.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
Process 27654 terminated.

**Comment by MinaSamir11** [comment]
@mToutounjy  I hope new release will solve your issue .
please check it out version 2.1.5. and give me feedback again.

**Comment by MinaSamir11** [comment]
**Update** this bug solved on **@2.1.7**

> > > @MinaSamir11  i have tested V2.1.4 and the problem still exist. Also if the Play Store app was disabled the app will crash too
> > 
> > 
> > But If playstore is not installed, crash with you too!!
> 
> yes
> 
> I/ReactNativeJS: RequestInAppReview
> I/PlayCore: UID: [10082] PID: [27654] ReviewService : requestInAppReview (xxx.xxx.xxx)
> I/PlayCore: UID: [10082] PID: [27654] ReviewService : Initiate binding to the service.
> I/PlayCore: UID: [10082] PID: [27654] ReviewService : Failed to bind to the service.
> E/isPlayStoreInstalled: true
> D/AndroidRuntime: Shutting down VM
> E/AndroidRuntime: FATAL EXCEPTION: main
> Process: xxx.xxx.xxx, PID: 27654
> com.google.android.play.core.tasks.RuntimeExecutionException: com.google.android.play.core.internal.aq: Failed to bind to the service.
> at com.google.android.play.core.tasks.m.getResult(Unknown Source:16)
> at com.ibits.react_native_in_app_review.AppReviewModule.lambda$show$1$AppReviewModule(AppReviewModule.java:53)
> at com.ibits.react_native_in_app_review.-$$Lambda$AppReviewModule$bUmS5pB5E-8STvn0S-VVfLR6ozE.onComplete(Unknown Source:4)
> at com.google.android.play.core.tasks.a.run(Unknown Source:23)
> at android.os.Handler.handleCallback(Handler.java:790)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6494)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> Caused by: com.google.android.play.core.internal.aq: Failed to bind to the service.
> at com.google.android.play.core.internal.ap.a(Unknown Source:78)
> at com.google.android.play.core.internal.ai.a(Unknown Source:4)
> at com.google.android.play.core.internal.ag.run(Unknown Source:0)
> at android.os.Handler.handleCallback(Handler.java:790)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:164)
> at android.os.HandlerThread.run(HandlerThread.java:65)
> Process 27654 terminated.

**Comment by hotaryuzaki** [comment]
any solution for this?

**Comment by hotaryuzaki** [comment]
i update the latest version and using emulator without play store, there is an error.
is same if i disable the play store.
but is okay because apps not crash.
