### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by mars-lan** [MinaSamir11/react-native-in-app-review#16]
Could you start keeping a proper changelog file or make use of GitHub releases so users don't have to go through the commit history to figure out the changes? See https://github.com/zoontek/react-native-permissions for an example.

**Comment by grit96** [comment]
This will help for people who use dependency bots like renovate

**Comment by cristianoccazinsp** [comment]
Would be great to have a changelog!

**Comment by grit96** [comment]
What changed between 2.1.8 and 3.1.0? Looking at the commit history it's difficult to see why this was a major version bump and what steps need to be taken to upgrade.

**Comment by MinaSamir11** [comment]
is change-log doc. well and satisfied or it needs to enhance?!

**Comment by mars-lan** [comment]
https://github.com/MinaSamir11/react-native-in-app-review/releases this looks great thanks!
