### ISSUE TITLE
Its not working in IOS Testflight Build

### ISSUE THREAD

**Issue by komelabbbas** [MinaSamir11/react-native-in-app-review#17]
In Android it working Fine. but in iOS TestFlight modal not showing.

try {
    const isAvailable = await InAppReview.isAvailable();

    if (!isAvailable) {
      return;
    }

    InAppReview.RequestInAppReview();
  } catch (e) {}

**Comment by mToutounjy** [comment]
@komelabbbas 
https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review

**Comment by komelabbbas** [comment]
Thanks
