### ISSUE TITLE
Review or rating pop up not opening

### ISSUE THREAD

**Issue by Altaf94** [MinaSamir11/react-native-in-app-review#180]
As it fall in the right condition and return true but in android physical device it is not opening the pop up

**Comment by MCvanderBerg** [comment]
I'm having a similar issue, have you find a solution @Altaf94?

**Comment by vishaledkey** [comment]
It might be because of https://developer.android.com/guide/playcore/in-app-review#quotas
@MCvanderBerg @Altaf94

**Comment by james-ovens-eurostar** [comment]
In my experience it would not show up on anything except the prod build that was distributed through the play store.

**Comment by MinaSamir11** [comment]
> As it fall in the right condition and return true but in android physical device it is not opening the pop up

please read the doc. well, it says that it's working on production or through internal testing.

**Comment by Altaf94** [comment]
Hi, I hope you’re doing well! My problem is now solved, but if anyone has any issues with in-app reviews, feel free to reach out—I’d be happy to help!

**Comment by Altaf94** [comment]
I have developed a custom native module for React Native and successfully bridged it into my React Native application without using any external libraries. The in-app functionality is complete and working perfectly.

**Comment by MinaSamir11** [comment]
> Hi, I hope you’re doing well! My problem is now solved, but if anyone has any issues with in-app reviews, feel free to reach out—I’d be happy to help!

No Thank you we are following an in-app-review, it's a trusted package.

**Comment by syedamiralieijtwaal** [comment]
Please share it @Altaf94 
show your approach
