### ISSUE TITLE
Any plans to support iOS?

### ISSUE THREAD

**Issue by daveyjones** [MinaSamir11/react-native-in-app-review#2]
I've been using this for iOS: https://github.com/oblador/react-native-store-review

I'm sure many developers (including myself) would appreciate a platform-agnostic module!

**Comment by daveyjones** [comment]
Looks like this module has both already: https://github.com/KjellConnelly/react-native-rate

But I think most developers searching for this are going to google "react native in-app review", so I think this library has the potential to surpass the other module simply because of the better name...

**Comment by AllanKlaus** [comment]
I think you didn't read the [in-app-review doc](https://developer.android.com/guide/playcore/in-app-review).
Android only is a limitation from the google api.

**Comment by daveyjones** [comment]
@AllanKlaus This is a React Native module. The purpose of a React Native module is to make native functionality accessible via JavaScript. In cases where both Android and iOS have equivalent native functionality, it makes sense that a React Native module would work on both platforms. In this case, this module exposes the relevant [Android API](https://developer.android.com/guide/playcore/in-app-review), but not the equivalent [iOS API](https://developer.apple.com/documentation/storekit/skstorereviewcontroller). As I pointed out earlier, there are already other modules that provide in-app reviews on both platforms, but I think this module has a better name—i.e. it is more likely to be at the top of a Google search when developers are searching for solutions, so it could easily become the go-to module for in-app reviews if iOS support was added.

**Comment by AllanKlaus** [comment]
@daveyjones got it. thanks for showing me this. I use react native but I never compiled anything to iOS, for me was unique to Android to review  because they launched it last week. Now that use send the iOS API I saw that they have it for much more time.

**Comment by MinaSamir11** [comment]
@daveyjones moving on to support iOS, and i would like to thank for supporting this package, and i will work hard and fastest to find supporting to iOS module.

**Comment by eltomali** [comment]
Yes, I totally agree with @daveyjones . It would be great to have support for in-app review for iOS as well from this module. @MinaSamir11 have you come a long way on implementing it for iOS ?

**Comment by ravirupareliya** [comment]
@eltomali @daveyjones @AllanKlaus  It is already there, take a look at https://github.com/ravirupareliya/rn-in-app-review

**Comment by MinaSamir11** [comment]
@eltomali i'm going to publish new npm release to support iOS, few hours or a day almost.

**Comment by MinaSamir11** [comment]
finally, Package updated to support rating on iOS

**Comment by ravirupareliya** [comment]
I loves the way you quickly copied code from my library which is already build 😀😀
Really appreciate it

**Comment by MinaSamir11** [comment]
> I loved the way you quickly copied code from my library which is already build 😀😀
> Really appreciate it

**Ok**

**Comment by daveyjones** [comment]
Thanks @MinaSamir11! I'm integrating this into my project now!
