### ISSUE TITLE
Crash on Android when PlayStore is disabled

### ISSUE THREAD

**Issue by ogard** [MinaSamir11/react-native-in-app-review#20]
Steps to reproduce:
1. Settings -> Apps -> Google Play Store -> Disable
2. Trigger rating from app using this library
3. App crashes

Environment:
- react-native: "0.63.4"
- Android SDK Build Tools: "29.0.5"
- Device android version: "7.0"

**Comment by ogard** [comment]
Looks to me that `task.getResult().toString()` throws unhandled exception `com.google.android.play.core.tasks.RuntimeExecutionException: com.google.android.play.core.internal.aq: Failed to bind to the service.`, which further makes app to crash.
File: `AppReviewModule.java`, line 59

**Comment by MinaSamir11** [comment]
Can you try the new version react-native-in-app-review@2.1.6 
and give me feedback?

**Comment by ogard** [comment]
@MinaSamir11 Still the same. There is unhandled exception in `msg` argument of `Log.e`. I'll make PR and add you as reviewer.

**Comment by MinaSamir11** [comment]
**Thank you.**
Branch merged and changes is live now @2.1.7.
