### ISSUE TITLE
android not showing rate popup :  Class not found when unmarshalling: com.google.android.play.core.review.b

### ISSUE THREAD

**Issue by stam-ops** [MinaSamir11/react-native-in-app-review#25]
Hello,

Works on android 9 but on android 10 we have the following error , any idea why 
 **Class not found when unmarshalling: com.google.android.play.core.review.b**
?
Thanks

12660 13967 I PlayCore: UID: [10475]  PID: [12660] ReviewService : requestInAppReview (com.xxx)
01-14 09:19:34.204 12660 14303 I PlayCore: UID: [10475]  PID: [12660] ReviewService : Initiate binding to the service.
01-14 09:19:34.205 12660 13967 E isGooglePlayServicesAvailable: true
01-14 09:19:34.214 12660 12660 I PlayCore: UID: [10475]  PID: [12660] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
01-14 09:19:34.215 12660 14303 I PlayCore: UID: [10475]  PID: [12660] ReviewService : linkToDeath
01-14 09:19:34.239 12660 14303 I PlayCore: UID: [10475]  PID: [12660] ReviewService : Unbind from service.
01-14 09:19:34.239 12660 12945 I PlayCore: UID: [10475]  PID: [12660] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
01-14 09:19:34.244  4941 15698 I ActivityTaskManager: START u0 {cmp=com.xxxx/com.google.android.play.core.common.PlayCoreDialogWrapperActivity (has extras)} from uid 10475
01-14 09:19:34.245  4941 15698 E Parcel  : Class not found when unmarshalling: com.google.android.play.core.review.b
01-14 09:19:34.245  4941 15698 E Parcel  : java.lang.ClassNotFoundException: com.google.android.play.core.review.b
01-14 09:19:34.245  4941 15698 E Parcel  :      at java.lang.Class.classForName(Native Method)
01-14 09:19:34.245  4941 15698 E Parcel  :      at java.lang.Class.forName(Class.java:454)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.Parcel.readParcelable(Parcel.java:2981)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.Parcel.readValue(Parcel.java:2883)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.BaseBundle.getString(BaseBundle.java:1160)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.content.Intent.getStringExtra(Intent.java:8548)
01-14 09:19:34.245  4941 15698 E Parcel  :      at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790)
01-14 09:19:34.245  4941 15698 E Parcel  :      at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694)
01-14 09:19:34.245  4941 15698 E Parcel  :      at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1932)
01-14 09:19:34.245  4941 15698 E Parcel  :      at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625)
01-14 09:19:34.245  4941 15698 E Parcel  :      at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707)
01-14 09:19:34.245  4941 15698 E Parcel  :      at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603)
01-14 09:19:34.245  4941 15698 E Parcel  :      at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.Binder.execTransactInternal(Binder.java:1056)
01-14 09:19:34.245  4941 15698 E Parcel  :      at android.os.Binder.execTransact(Binder.java:1029)
01-14 09:19:34.245  4941 15698 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.google.android.play.core.review.b
01-14 09:19:34.245  4941 15698 E Parcel  :      ... 20 more
01-14 09:19:34.246  4941 15698 W Bundle  : Failed to parse Bundle, but defusing quietly
01-14 09:19:34.246  4941 15698 W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.play.core.review.b
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.Parcel.readParcelableCreator(Parcel.java:3059)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.Parcel.readParcelable(Parcel.java:2981)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.Parcel.readValue(Parcel.java:2883)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.BaseBundle.getString(BaseBundle.java:1160)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.content.Intent.getStringExtra(Intent.java:8548)
01-14 09:19:34.246  4941 15698 W Bundle  :      at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790)
01-14 09:19:34.246  4941 15698 W Bundle  :      at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694)
01-14 09:19:34.246  4941 15698 W Bundle  :      at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1932)
01-14 09:19:34.246  4941 15698 W Bundle  :      at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625)
01-14 09:19:34.246  4941 15698 W Bundle  :      at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707)
01-14 09:19:34.246  4941 15698 W Bundle  :      at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603)
01-14 09:19:34.246  4941 15698 W Bundle  :      at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.Binder.execTransactInternal(Binder.java:1056)
01-14 09:19:34.246  4941 15698 W Bundle  :      at android.os.Binder.execTransact(Binder.java:1029)

**Comment by MinaSamir11** [comment]
what is version of the package ?

**Comment by stam-ops** [comment]
"react-native-in-app-review": "^2.1.7",
Galaxy S9, Android 10

**Comment by MinaSamir11** [comment]
I miss understand your issue, this logs crash happen on production, or logs founded while in debugging mode ?

**Comment by stam-ops** [comment]
Both, I tried on debugging and with a release version

**Comment by stam-ops** [comment]
same build works on Android 9

**Comment by MinaSamir11** [comment]
ok this logs seems you pick up it from debugging (android studio logs) and this happen because in app review in android doesn't work in debugging, so this logs appears normal in debug apk.  but abnormal that app has crash ?
- Is app crash with you ?

- Is this scenario what I assume happening now ?

**and please note:** 
rating popup will not shown because it require your app to be published in Play Store. However, you can test your integration without publishing your app to production using either internal test tracks or internal app sharing.

**Comment by stam-ops** [comment]
Same bug with release version published in Play Store with internal test
01-14 10:20:44.982  4941 13548 E Parcel  : Class not found when unmarshalling: com.google.android.play.core.review.b
01-14 10:20:44.982  4941 13548 E Parcel  : java.lang.ClassNotFoundException: com.google.android.play.core.review.b
01-14 10:20:44.982  4941 13548 E Parcel  :      at java.lang.Class.classForName(Native Method)

**Comment by MinaSamir11** [comment]
may this solution will work with you try out it : 
https://github.com/google/play-unity-plugins/issues/60#issuecomment-733683055 

if not success try in production with different Gmail that has not reviewed yet your app.

**Comment by stam-ops** [comment]
thank you for your help but I have the same error with another account ;(

**Comment by stam-ops** [comment]
finally It worked with another google account ....

**Comment by alex1blackhole** [comment]
same error,tested on the meizu/honor both android 6 and meizu android 9  , debug and release 
InAppReview.isAvailable();  return true , but nothing happens next 
the app is available in playMarket , Also switched to different accounts nothing has changed

on ios work very well , emulator and device (iphone SE ) 

buildToolsVersion = "29.0.2"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29

**Comment by MinaSamir11** [comment]
> same error,tested on the meizu/honor both android 6 and meizu android 9  , debug and release 
> InAppReview.isAvailable();  return true , but nothing happens next 
> the app is available in Google Play, also switched to different accounts nothing has changed
> 
> on ios work very well , emulator and device (iphone SE ) 
> 
> "react-native-in-app-review": "^2.1.7",
> 
> buildToolsVersion = "29.0.2"
> minSdkVersion = 21
> compileSdkVersion = 29
> targetSdkVersion = 29
> 

You have to build new release include package and upload it to production or you can test integration using internal app sharing. 

 this ans. Will help you.

https://github.com/MinaSamir11/react-native-in-app-review/issues/6#issuecomment-699482016

**Comment by MinaSamir11** [comment]
> finally It worked with another google account ....

It works fine now?

**Comment by desmondmc** [comment]
I'm having this issue and it doesn't seem to be related to test user emails or even Android 10. It works on my main Android test phone which is running stock Android 10.

I've been able to reproduce it on 3 other devices and they are all Samsung devices running Android 10. Could this be an issue specific to Samsung phones?
