### ISSUE TITLE
How to know if the review alert was shown or not? (analytics purposes)

### ISSUE THREAD

**Issue by petercvek** [MinaSamir11/react-native-in-app-review#26]
I would like to track if the review alert was opened or not when calling a function InAppReview.RequestInAppReview(), some kind of callback or something so I could track if the review was already done by the user or not.

It's for analytics purposes, to know how many times we showed the user app review alert, and has closed it and if the alert was not showed then we can predict that the user already gave a review.

**Comment by MinaSamir11** [comment]
Going todo it :)

**Comment by kangpeter5** [comment]
@MinaSamir11 Any luck? Could really use this for the same reasons as @petercvek

**Comment by MinaSamir11** [comment]
@kangpeter5, working on updating docs...

**Comment by Doha26** [comment]
Hey @MinaSamir11  i'm also waiting for this feature. is there any update ?

**Comment by MinaSamir11** [comment]
@Doha26 I'm updating it now, please wait till tomorrow may i release new version...

**Comment by MinaSamir11** [comment]
- Update is live now, update package and reset npm cache.. 
- **Please Note**, Considering this changes as beta release if you face any problems. open new issue thank you...

Tell me if new changes meet you requirements or not..

**Comment by MinaSamir11** [comment]
I'm closing this issue, because these feature add in version 3.1.0.

**Comment by SamiChab** [comment]
@MinaSamir11 I dont see anywhere in the docs where the library returns the info about if a user has already reviewed the app or not. Or does the function `InAppReview.isAvailable()` return false if the user has already reviewed ?
