### ISSUE TITLE
Crashing on android

### ISSUE THREAD

**Issue by trtq** [MinaSamir11/react-native-in-app-review#28]
On ios, reviews work flawlessly. On android, trying to run the app after installing crashes for us with this error.

```
error: package com.ibits.react_native_in_app_review does not exist
import com.ibits.react_native_in_app_review.AppReviewPackage;
                                           ^
 error: cannot find symbol
      new AppReviewPackage(),
          ^
  symbol:   class AppReviewPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugJavaWithJavac'.
```

Trying to fix this, i turned off automatic linking via _react-native.config.js_ and tried to manually link the package, but it crashes with the same error.

Environment:
React native version: **0.63.3**
Device android version: any (the app crashes on the point of building, before any code is injected on the device)

**Comment by JonathasLopes** [comment]
I have the same problem .. did you get anything to solve this problem?

**Comment by MinaSamir11** [comment]
@trtq @JonathasLopes 
Did you resolve the issue of not?

Try to add this in this path ( android/settings.gradle): 
include ':react-native-in-app-review'
project(':react-native-in-app-review').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-in-app-review/android')
