### ISSUE TITLE
Invalid revision with build.gradle

### ISSUE THREAD

**Issue by markchen8717** [MinaSamir11/react-native-in-app-review#29]
* Where:
Build file 'node_modules/react-native-in-app-review/android/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':react-native-in-app-review'.
> Invalid revision: "28.0.3"

**Comment by ralesiupgrade** [comment]
any word on this issue? im getting the same error, I tried cleaning and rebuilding and nothing

**Comment by markchen8717** [comment]
Here is what worked for me: 

- Go to android/build.gradle
- Inside the ext block, add: buildToolsVersion = "28.0.3" , change the version accordingly to the error you are receiving
- Clean and rebuild
