### ISSUE TITLE
TypeError: null is not an object (evaluating 'InAppReviewModule.show')

### ISSUE THREAD

**Issue by jigartankhupp** [MinaSamir11/react-native-in-app-review#3]
**Additional Information**
"react-native-in-app-review": "^1.0.5"
"react": "16.8.3",
"react-native": "0.59.9",
Platform(s) (iOS, Android, or both?): Android
Operating System : macOS

InAppReview.RequestInAppReview()

**Comment by MinaSamir11** [comment]
for react native 0.59.9 and below need manual linking please check doc again to see how to link library to your project
in-app-review working now on android platform only, for iOS platform moving on to support it.

**Comment by jigartankhupp** [comment]
**Error:**

/node_modules/react-native-in-app-review/android/src/main/java/com/ibits/react_native_in_app_review/AppReviewPackage.java:3: error: cannot find symbol
import androidx.annotation.NonNull;

**Comment by MinaSamir11** [comment]
@jigartankhupp  add this:

**in android/gradle.properties**

android.useAndroidX=true
android.enableJetifier=true

**Comment by MinaSamir11** [comment]
If the solution above don't need to do it. Inform me
