### ISSUE TITLE
Review not showing on Android emulator

### ISSUE THREAD

**Issue by cjinghong** [MinaSamir11/react-native-in-app-review#31]

**Comment by MinaSamir11** [comment]
+ please read guidelines related  to android for reviews: 
 - https://github.com/MinaSamir11/react-native-in-app-review#please-note-to-test-your-integration-using-the-google-play-store
 - duplicated issue : https://github.com/MinaSamir11/react-native-in-app-review/issues/6#issuecomment-699482016
