### ISSUE TITLE
is it MUST to upload to play store for every change?

### ISSUE THREAD

**Issue by hotaryuzaki** [MinaSamir11/react-native-in-app-review#32]
my prod apps already in play store, so because of that i think for Dev/Staging apps i could tried:
1. install Debug from CLI => pop up not show
2. install Release from CLI => pop up not show
3. install Release from APK => pop up not show

but when i open Play Store it detects the apps already installed, but none of them show any pop up.
is it MUST to upload to play store for every change and download again from play store?

NOTE:
- i tried use different Gmail account
- The user has not yet rated the apps in Play Store

**Comment by MinaSamir11** [comment]
yes you have to build bundle after integrate with package, and upload it to production and install app from play store when it became live with new release. after that popup will appear.

**Comment by hotaryuzaki** [comment]
> yes you have to build bundle after integrate with package, and upload it to production and install app from play store when it became live with new release. after that popup will appear.

hmmm, ok..
i will try internal app sharing.

**Comment by hotaryuzaki** [comment]
> yes you have to build bundle after integrate with package, and upload it to production and install app from play store when it became live with new release. after that popup will appear.

oh sorry i have 1 more question, are you have any plan to create React Native in-app-update package? :D

**Comment by MinaSamir11** [comment]
> in-app-update

let me take a look, about time that i will spent on it. and tell you the date. :)

**Comment by hotaryuzaki** [comment]
> > in-app-update
> 
> let me take a look, about time that i will spent on it. and tell you the date. :)

الحمدالله
بارك الله فيكم

أمري الإندونيسي

**Comment by hotaryuzaki** [comment]
> yes you have to build bundle after integrate with package, and upload it to production and install app from play store when it became live with new release. after that popup will appear.
 
i tried internal sharing app today,
1. emulator with play store -> pop up not show
2. Android phone with OS 10 and different gmail account -> pop up not show

apps freshly installed from internal sharing app download link

my code is just simple
```
// Give you result if version of device supported to rate app or not!
const inappreview_available = InAppReview.isAvailable();
console.log(inappreview_available); // show true

// trigger UI InAppreview
InAppReview.RequestInAppReview();
```

**Comment by hotaryuzaki** [comment]
> > yes you have to build bundle after integrate with package, and upload it to production and install app from play store when it became live with new release. after that popup will appear.
> 
> hmmm, ok..
> i will try internal app sharing.

it works from real device!
from emulator show nothing even it has Play store on it, maybe Google check the device.
بارك الله فيكم

**Comment by MinaSamir11** [comment]
> from emulator show nothing even it has Play store on it, maybe Google check the device.

- it's not working on emulator since reviews must be real and trusted that it's coming from real user.  
- it's blocked on emulator for security.
