### ISSUE TITLE
In Android, the in app review pop up does not appear

### ISSUE THREAD

**Issue by dion-george** [MinaSamir11/react-native-in-app-review#33]
The app was first downloaded from Play Store and currently does not have a review for the app.
Then I added this package and while running the app on the device using Android Studio I'm getting InAppReview.isAvailable()   as true but nothing opens.

**Comment by MinaSamir11** [comment]
Read this carefully 👍 for testing =>
Test using an internal test track:
Upload your app to the internal test track and install it on a device with a user account that has access to the internal test track. When using an internal test track, the following conditions must be met:

1 - The user account in the Play Store has downloaded the app from the Play Store. When this is the case, the app is listed in the user's Google Play library.
2- The user does not currently have a review for the app.
3- The quota has not been reached.

After the account on the device has downloaded the app at least once from the internal test track and is part of the testers list, you can deploy new versions of the app locally to that device (for example, using Android Studio).

RECOMMENDED: Test using internal app sharing:
Alternatively, for rapid iteration you can use internal app sharing to test your integration. This method lets you quickly test changes by skipping some of the verification that happens with other test tracks.

Important: When using an app installed with internal app sharing, reviews can't be submitted. To emphasize this difference, the button is disabled in the UI.

OR Publish your new release to production after integration, to trigger UI
without one of 3 options above, UI will not triggered.

**Comment by MinaSamir11** [comment]
This issue marked as duplicated: https://github.com/MinaSamir11/react-native-in-app-review/issues/32#issuecomment-776629228
