### ISSUE TITLE
Unable to start service Intent

### ISSUE THREAD

**Issue by ridik1803** [MinaSamir11/react-native-in-app-review#4]
Error after calling `InAppReview.RequestInAppReview()` (logcat logs):
`Unable to start service Intent { act=com.google.android.finsky.BIND_IN_APP_REVIEW_SERVICE pkg=com.android.vending } U=0: not found`
`PlayCore: UID: [10159]  PID: [2298] ReviewService : Failed to bind to the service.`
`com.google.android.play.core.tasks.RuntimeExecutionException: com.google.android.play.core.internal.aq: Failed to bind to the service.`

"react-native-in-app-review": "^1.0.5"
"react": "16.11.0",
"react-native": "0.62.2",
Platform(s) (iOS, Android, or both?): Android

**Comment by MinaSamir11** [comment]
@ridik1803  please can you mention the device you are testing on it, real or virtual, and details that device ?
and the API level of the android  ?!
 **try using**: real device if you are using simulator. 
**Make sure that In-app reviews require your app to be published in Play Store. However, you can test your integration without publishing your app to production using either internal test tracks or internal app sharing.**

**Comment by ridik1803** [comment]
@MinaSamir11  I tried emulator and real device (Samsung A50 Android 10). My application has already published

**Comment by MinaSamir11** [comment]
Did you build a new release after adding library, and publish new release to production OR you have publish  release in test using internal test tracks or internal app sharing.??

Testing in-app-review will not work in debug apk.

**Comment by MinaSamir11** [comment]
Read this carefully 👍 for testing => 
**Test using an internal test track**
Upload your app to the internal test track and install it on a device with a user account that has access to the internal test track. When using an internal test track, the following conditions must be met:

1 - The user account in the Play Store has downloaded the app from the Play Store. When this is the case, the app is listed in the user's Google Play library.
2- The user does not currently have a review for the app.
3- The quota has not been reached.

After the account on the device has downloaded the app at least once from the internal test track and is part of the testers list, you can deploy new versions of the app locally to that device (for example, using Android Studio).


**Test using internal app sharing**
Alternatively, for rapid iteration you can use [internal app sharing](https://play.google.com/apps/publish/internalappsharing/) to test your integration. This method lets you quickly test changes by skipping some of the verification that happens with other test tracks.

Important: When using an app installed with internal app sharing, reviews can't be submitted. To emphasize this difference, the button is disabled in the UI.
__________________________________________________________________________
_**OR**_ **Publish your new release to production** .
