### ISSUE TITLE
No Pop Up displayed, while app is in development mode

### ISSUE THREAD

**Issue by durgeshgit20** [MinaSamir11/react-native-in-app-review#40]
Hello,
I am using react-native-in-app-review@2.1.8 version..

while my app is in development mode ..
i just wanted to see how the dialog box is displayed in App

however nothing happens when is following code is executed in component didMount..

if(days>15  && InAppRevew.isAvailable()){
InAppReview.requestInAppReview();
}

according to the documentation ,if the application is in developement , i should atleast be able to see the pop up dialog box,right ?

help would be appreciated thanks...

**Comment by MinaSamir11** [comment]
Not right, you can see Pop up only in iOS devices, and in android you have to integrate with package after that upload new bundle to internal testing OR production to see pop up .
Duplicated issue: https://github.com/MinaSamir11/react-native-in-app-review/issues/6#issuecomment-699482016
