### ISSUE TITLE
Question: in app review android message required

### ISSUE THREAD

**Issue by psyzz** [MinaSamir11/react-native-in-app-review#42]
Hello, thanks for this great library !

i tested it on internal test android, but the message is required to review the app.
In your description you said that the message should be optional.
Is there any modification i need to do ?

Regards

**Comment by psyzz** [comment]
Ok i push my update on production and the message is now "optional" 👯

**Comment by orhangazi** [comment]
> Ok i push my update on production and the message is now "optional" 👯

Thank you for info
