### ISSUE TITLE
Do not hardcode play-services versions

### ISSUE THREAD

**Issue by cristianoccazinsp** [MinaSamir11/react-native-in-app-review#43]
Current build.gradle file has `implementation 'com.google.android.gms:play-services-base:17.5.0'`.

This can be problematic if other incompatible libraries are used, please make this a build time variable, similar to what other libraries do. For instance:

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}


dependencies {
  implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
  implementation "com.android.installreferrer:installreferrer:${safeExtGet('installReferrerVersion', '1.1.2')}"
}


```

Latest version: https://developers.google.com/android/guides/setup

**Comment by cristianoccazinsp** [comment]
@MinaSamir11 was this addressed?

**Comment by MinaSamir11** [comment]
@cristianoccazinsp 

Thank you @cristianoccazinsp  
You are right. 

I do it in compileSdkVersion & targetSdkVersion,..
I forget to add it to lib.
