### ISSUE TITLE
Is it possible to track How many stars did the user put?

### ISSUE THREAD

**Issue by mitaxe** [MinaSamir11/react-native-in-app-review#45]
Hey. A simple question. Is it possible to track how many stars did the user put or it's a limitation?

**Comment by MinaSamir11** [comment]
No, google play or play store doesn't provide us any info, about user opinion. Just launch review flow, and let user free do what he want and review your dashboard of one of any store. To see users reviews and rating. These plugin works according to rules of play store and app store lib.
