### ISSUE TITLE
InAppReview.RequestInAppReview() not working white npm run android

### ISSUE THREAD

**Issue by johansmith** [MinaSamir11/react-native-in-app-review#46]
Hello friend, thanks for your plugin, I am testing directly from the terminal with npm run android to a physical device, but it does not work. Should I upload a trial version to the PLAY STORE? Or with testing the android npm run should it work?

**Comment by MinaSamir11** [comment]
Hello 👋, the result you got it's the normally, that it doesn't work on debugging mode, you should upload it to play store after integrate with plugin to see review flow. (android)
For ios it appears in debugging mode.

**Comment by johansmith** [comment]
Thanks for your answer. You're the best
