### ISSUE TITLE
How know if the user reviewed or not

### ISSUE THREAD

**Issue by johansmith** [MinaSamir11/react-native-in-app-review#47]
Hi, How can I know if the current user has reviewed the application or not? I need to show the InAppReview.RequestInAppReview () window only if the user has not voted, or else it would be spam

**Comment by NgocNamFNT** [comment]
Let me ask if your android shows review

**Comment by tarouboy** [comment]
I think you have to log it somewhere by yourself. Easiest way will be using [AsyncStorage](https://github.com/react-native-async-storage/async-storage).

**Comment by NgocNamFNT** [comment]
> I think you have to log it somewhere by yourself. Easiest way will be using [AsyncStorage](https://github.com/react-native-async-storage/async-storage).
android is not show popup

**Comment by MinaSamir11** [comment]
@johansmith  
according to given from iOS, android API :->
When the flow has finished. The API does not indicate whether the user reviewed or not, or even whether the review dialog was shown. Thus, no matter the result, we continue our app flow.

- But you can benefit from these issue  
 https://github.com/MinaSamir11/react-native-in-app-review/issues/26

**Comment by MinaSamir11** [comment]
> > I think you have to log it somewhere by yourself. Easiest way will be using [AsyncStorage](https://github.com/react-native-async-storage/async-storage).
> > android is not show popup

Your issue was duplicated you can read this:
https://github.com/MinaSamir11/react-native-in-app-review/issues/6
