### ISSUE TITLE
pushing app in background

### ISSUE THREAD

**Issue by MriduDixit15** [MinaSamir11/react-native-in-app-review#48]
when i call InAppReview.RequestInAppReview() function , pushing app to the background

**Comment by MinaSamir11** [comment]
can you put what type of error you are facing ?

**Comment by MriduDixit15** [comment]
on calling review function, appstate change event emitting
*AppState.addEventListener('change', this._handleAppStateChange)*
and appstate is change to background

**Comment by MinaSamir11** [comment]
I'm not understanding if it error happen or you mean that you are tracking event appState and you got that your app goes to background state if that, what is your issue if triggering UI makes the app in the background !!!!!.
