### ISSUE TITLE
Work with Expo?

### ISSUE THREAD

**Issue by GollyJer** [MinaSamir11/react-native-in-app-review#5]
I noticed this doesn't need to be linked, explicitly, but is that because links automatically? Or is there really no need to link; which means it will work with an Expo managed app?

Thanks!

**Comment by mateusw3c** [comment]
I tried using it at the expo but it didn't work :(

**Comment by MinaSamir11** [comment]
@GollyJer  it must be work with expo normally!
 did you face any problem ?
 can you show issue appears to you?

**Comment by MinaSamir11** [comment]
@mateusw3c  please can you tell me what happen ! 
OR what do you do starting from Installing lib ?

**Comment by MinaSamir11** [comment]
@GollyJer  @mateusw3c  Going to create pull request with expo

**Comment by mateusw3c** [comment]
I solved my problem using [expo-store-review](https://github.com/expo/expo/tree/sdk-39/packages/expo-store-review) package for expo. This solution need expo v^39.0.0.

**Comment by Hosam-hsm** [comment]
But when I used the expo-store-review package, the review modal only showed once on the first build only. I thought it was because I already rated the app and so I removed my ratings for the app in the stores. But it is not showing the modal. Any idea on that?

**Comment by mateusw3c** [comment]
It's a quota problem.

https://developer.android.com/guide/playcore/in-app-review#quotas

> To provide a great user experience, Google Play enforces a time-bound quota on how often a user can be shown the review dialog. Because of this quota, calling the launchReviewFlow method more than once during a short period of time (for example, less than a month) might not always display a dialog.
> 
> Because the quota is subject to change, it's important to apply your own logic and target the best possible moment to request a review. For example, you should not have a call-to-action option (such as a button) to trigger the API, as a user might have already hit their quota and the flow won’t be shown, presenting a broken experience to the user. For this use case, redirect the user to the Play Store instead.

**Comment by Hosam-hsm** [comment]
Great. Thanks!

**Comment by MinaSamir11** [comment]
I'm closing this issue.

If you use Expo to create a project [you'll just need to](https://facebook.github.io/react-native/docs/getting-started#caveats) "[eject](https://docs.expo.io/versions/latest/expokit/eject)".

  ```bash
 expo eject
 ```

 ```
-> Then install package normally: 

npm install react-native-in-app-review
 ```
