### ISSUE TITLE
Unable to determine Swift version for Pod

### ISSUE THREAD

**Issue by Pedrohocastro** [MinaSamir11/react-native-in-app-review#58]
![Captura de Tela 2021-06-22 às 17 33 40](https://user-images.githubusercontent.com/9091316/122995497-11a17280-d380-11eb-98e6-f147dc5ddee5.png)

how can i fix that?

**Comment by MinaSamir11** [comment]
I will resolve this issue with you:

1- run ```npm uninstall react-native-in-app-review ``` to remove old package.
2 after that, run ```npm install git://github.com/MinaSamir11/react-native-in-app-review.git#solve-bug-unable-to-determine-swift-version --save ``` to install the beta of the new version package before update the package to your issue. 
3- try again to run ```npx pod-install```, to see if the issue resolved or still exists.

**Comment by Pedrohocastro** [comment]
Pod install is now working properly.
But i still cant run the project. This generated 52 erros.

![Captura de Tela 2021-06-23 às 10 59 49](https://user-images.githubusercontent.com/9091316/123110302-5544bc80-d412-11eb-90e3-a28c764301ee.png)

**Comment by MinaSamir11** [comment]
what's your react native version ?

**Comment by Pedrohocastro** [comment]
"react-native": "0.61.4"

**Comment by MinaSamir11** [comment]
try these steps: 
1- Open ios/YourAppName.xcodeproj in Xcode
2- Right-click on Your App Name in the Project Navigator on the left, and click New File…
3- Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
4- when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
This should fix the problem

**Comment by Pedrohocastro** [comment]
> try these steps:
> ![165921](https://user-images.githubusercontent.com/48614170/123204704-ea01f580-d4b8-11eb-9966-a6c0b0e7dacc.png)
> 
> 1- Open ios/YourAppName.xcodeproj in Xcode
> 2- Right-click on Your App Name in the Project Navigator on the left, and click New File…
> 3- Create a single empty Swift file to the project (make sure that Your App Name target is selected when adding)
> 4- when Xcode asks, press Create Bridging Header and do not remove Swift file then. re-run your build.
> This should fix the problem

It's working now!
Thanks

**Comment by MinaSamir11** [comment]
Remove installed current package. 
and install new version v3.2.2 now. Update live now.

**Comment by ttristan** [comment]
I also face this issue when adding v3.2.3

I have created the file as you suggested and created the Bridge Header, but it did not help.

RN 0.63.4, Xcode 13.0, M1 MacBook Air
Podfile platform :ios, '10.3'

<img width="508" alt="Screenshot 2021-10-14 at 22 04 06" src="https://user-images.githubusercontent.com/24268434/137387624-d224018b-c71f-41a4-b061-2dd2c340a23d.png">

<img width="500" alt="Screenshot 2021-10-14 at 22 01 41" src="https://user-images.githubusercontent.com/24268434/137387498-8496e35c-7e8f-48a4-90c8-c74a2f4168bb.png">

**Comment by MinaSamir11** [comment]
@ttristan 
if you remove a package, it builds successfully !!
