### ISSUE TITLE
doesn't wok

### ISSUE THREAD

**Issue by mtalhagaoglu** [MinaSamir11/react-native-in-app-review#6]
Hi. I really love the idea but it didn't work for me. Triggering `InAppReview.RequestInAppReview();`  returns nothing to me. I tested on real device and simulator also my app is published on google play. because of there is no error i can't publish any error with you :-/

**Comment by MinaSamir11** [comment]
Read this carefully 👍 for testing =>
Test using an internal test track
Upload your app to the internal test track and install it on a device with a user account that has access to the internal test track. When using an internal test track, the following conditions must be met:

1 - The user account in the Play Store has downloaded the app from the Play Store. When this is the case, the app is listed in the user's Google Play library.
2- The user does not currently have a review for the app.
3- The quota has not been reached.

After the account on the device has downloaded the app at least once from the internal test track and is part of the testers list, you can deploy new versions of the app locally to that device (for example, using Android Studio).

Test using internal app sharing
Alternatively, for rapid iteration you can use internal app sharing to test your integration. This method lets you quickly test changes by skipping some of the verification that happens with other test tracks.

Important: When using an app installed with internal app sharing, reviews can't be submitted. To emphasize this difference, the button is disabled in the UI.

**Comment by mtalhagaoglu** [comment]
oh my app installed with apk not with google play. probably because of that it doesn't trigger. sorry for misunderstanding 🤦🏾‍♂️
