### ISSUE TITLE
Modal won't show up in production mode [Android]

### ISSUE THREAD

**Issue by ikotsov** [MinaSamir11/react-native-in-app-review#61]
Hello!

First of all great work and thank you for this package! I even show it included in a "React Status" newsletter which means this it is going very well 👍

Let me describe my issue.

I installed the package and tested it both in iOS and Android. I followed your instructions and used in app sharing for testing in Android and it worked fine.

The problem is that after deploying and downloading my app to Google Play Store I navigated to it in order to see if modal is shown indeed and it did not shown up. I tested it in three different Android devices.

I am thinking of some possible causes:

1. Are there any permissions configuration needed? I suppose, judging from the testing in development mode, that there is not any configuration needed and after installing the package it should work under the hood in production mode as well.
2. Might be that the devices do not meet the certain requirements needed for the in app review feature to be supported, but I double checked that all of them run at least Android 5.0 (API level 21).
3. Google might not show the modal for another reason, other than those described here (Google workspace account, device requirements, quota limit)?

Any insight would be helpful! Thank you!

**Comment by MinaSamir11** [comment]
Hello, 
Thank you @ikotsov 

Review flow will not appear if one of the following reasons occurs it may be very tricky:-> 

 1- The user account is protected (for example, with enterprise accounts), Probably your test devices used an email in the google play store that was made from G SUITE which for some reason does not work, log out from the test account gsuite email and log in with a private Gmail account inside of Google play store.
 
2- The user account has already reviewed the app, delete the review directly from Play Store.

3- Your app must be in the user's Google Play library. To add your app to the user's library, download your app from the Play Store using that user's account. **hypothesis(weak): in your case** you probably didn't remove the version of app sharing first and the production version overrides on the previous v., it may cause something cashed try to remove app and download again.

4- The primary account is not selected in the Play Store, When multiple accounts are available in the device, ensure that the primary account is the one selected in the Play Store.


5- There is an issue with the Google Play Store or Google Play Services on the device, this commonly occurs when the Play Store was sideloaded onto the device. Use a different device that has a valid version of the Play Store and Google Play Services.

Try again and give me feedback...
please list the devices models you test on it and their API level, if still issue exist. 

**_I hope you will find my comment helpful._**

**Comment by ikotsov** [comment]
Great answer! 👌

I thinks these bullets can be used as a reference for knowing how to debug whether the modal will finally appear or not in production mode.

There was not any collide in my case. I tried it in a device which did not ever have the version of the build which was available via internal app sharing.

I will try again and in case the problem persists, I will post again.

Will also add logging when the modal triggers so that I gain more data to count on.

Thank you very much for your quick and thorough answer!

PS: Just wanted to make sure that I do not miss something from my side as far as setting up the package is concerned. If this is issue comes from how Google works, then there is not much we can do.

**Comment by MinaSamir11** [comment]
Thank you, 
Any time to support.

Yes it comes from google but we try to follow there guidelines to make sure best practice to user, and make sure that our testing works well as in production too.

If there's any update post it you are welcome.
