### ISSUE TITLE
Review modal not showing despite success result

### ISSUE THREAD

**Issue by knevagi** [MinaSamir11/react-native-in-app-review#62]
So i am  trying to implement this package in my app. I created a modal which has a button that triggers RequestInAppReview() function. 

```
      function Rateus(){
        InAppReview.RequestInAppReview()
        .then((hasFlowFinishedSuccessfully) => {
    // when return true in android it means user finished or close review flow
    console.log('InAppReview in android', hasFlowFinishedSuccessfully);

    // when return true in ios it means review flow lanuched to user.
    console.log(
      'InAppReview in ios has lanuched successfully',
      hasFlowFinishedSuccessfully,
    );

    // 1- you have option to do something ex: (navigate Home page) (in android).
    // 2- you have option to do something,
    // ex: (save date today to lanuch InAppReview after 15 days) (in android and ios).

    // 3- another option:
    if (hasFlowFinishedSuccessfully) {
      // do something for ios
      // do something for android
    }

    // for android:
    // The flow has finished. The API does not indicate whether the user
    // reviewed or not, or even whether the review dialog was shown. Thus, no
    // matter the result, we continue our app flow.

    // for ios
    // the flow lanuched successfully, The API does not indicate whether the user
    // reviewed or not, or he/she closed flow yet as android, Thus, no
    // matter the result, we continue our app flow.
  })
  .catch((error) => {
    //we continue our app flow.
    // we have some error could happen while lanuching InAppReview,
    // Check table for errors and code number that can return in catch.
    console.log(error);
  });

      }
```

I am getting successfully launched console log but no modal is getting launched. My app is already on the play store. Is there any setup that i could be missing? Thanks in advance

**Comment by MinaSamir11** [comment]
Hello,
Hint: First you have to read doc readme well, to not let user banned to review your app on android.

According to your issue, you have miss understanding, about that your app must be on play store.
You have to integrate with package and after that release new update to play store. And try to test it again.

**Comment by knevagi** [comment]
Does it not work when released on internal testing in playstore? Because I did that but still I could not see the modal.

**Comment by knevagi** [comment]
Ok never mind looks like my review quota had reached so I couldn't see the modal. Closing this issue. Thanks.

**Comment by MinaSamir11** [comment]
> Does it not work when released on internal testing in playstore? Because I did that but still I could not see the modal.

It can work on internal testing too. 

> Ok never mind looks like my review quota had reached so I couldn't see the modal. Closing this issue. Thanks.

Try to use another gmail account, that doesn't review your app yet.

**Comment by MinaSamir11** [comment]
> Does it not work when released on internal testing in playstore? Because I did that but still I could not see the modal.

It can work on internal testing too. 

> Ok never mind looks like my review quota had reached so I couldn't see the modal. Closing this issue. Thanks.

Try to use another gmail account, that doesn't review your app yet.
-if you have reach quota it must work at least on internal app sharing, to test it, still facing issue about modal doesn't triggered ?!
