### ISSUE TITLE
Remove buildToolsVersion

### ISSUE THREAD

**Issue by sonywijaya** [MinaSamir11/react-native-in-app-review#64]
https://github.com/MinaSamir11/react-native-in-app-review/blob/217527fe17324e531f91391804fd83191eaa44f7/android/build.gradle#L32

I can't build the android project when I don't set buildToolsVersion in my project
Is it possible that you remove it? Since it's optional

**Comment by MinaSamir11** [comment]
- It takes the build tools version from your project if it does not exist it fallback to the defaults value which is 28.0.3. 
- Please list your error here maybe we can find another sol. since no one yet has the same issue build tools version to remove it.

**Comment by sonywijaya** [comment]
> * It takes the build tools version from your project if it does not exist it fallback to the defaults value which is 28.0.3.
> * Please list your error here maybe we can find another sol. since no one yet has the same issue build tools version to remove it.

I think the easiest solution is to set buildToolsVersion on my project or delete the buildToolsVersion safeExtGet('buildToolsVersion')  code from my node modules

**Comment by MinaSamir11** [comment]
Node modules every time will overide your changes, after run npm install

You have to define set build tools version on your project.

Thank you if you have any Questions youare welcomed.
