### ISSUE TITLE
Using gsuite email address will prevent reviews on android

### ISSUE THREAD

**Issue by JamesLarson** [MinaSamir11/react-native-in-app-review#65]
Please refer to this issue: https://issuetracker.google.com/issues/167352813#comment15

**Issue:** If the user is logged into google play with an account using a Gsuite email address. The in-app review prompt will fail to work however "hasFlowFinishedSuccessfully" will always return true. I followed all troubleshooting steps to verify nothing else was causing this issue. Switching to a @gmail.com email address as the logged in user in google play fixed the issue. I have not tested this with any non-gmail email accounts.  

**Suggested fix:** Until the bug is addressed by google, make note of this as a known issue in the readme file. It may save some people a lot of time and effort.

**Comment by MinaSamir11** [comment]
Thank you for your suggestion, appreciate that.
I believe that people have to see first closed issues, before going to invest their time in searching for their issue. 

https://github.com/MinaSamir11/react-native-in-app-review/issues/25
https://github.com/MinaSamir11/react-native-in-app-review/issues/61

You have a good point and I will update README. 
Thank again.

**Comment by JamesLarson** [comment]
Doing further testing, this issue seems to only happen when you are testing using an internal test track. If you use internal sharing, you can use Gsuite emails in google play and you will be shown the review prompt. I have not tested this in our production build yet but will come back here to report on that soon.
