### ISSUE TITLE
[QUESTION] is there a callback function to see if the user pressed cancel or submit on the rating modal?

### ISSUE THREAD

**Issue by nervouscat** [MinaSamir11/react-native-in-app-review#75]
Hello all,

I have a specific use case: Is there a callback function to see if the user pressed cancel or submit on the rating modal?

Thank you in advance!

**Comment by MinaSamir11** [comment]
No, google play or play store doesn't provide us any info, about user opinion. Just launch review flow, and let user free do what he want and check your dashboard of any store. To see users reviews and rating. These plugin works according to rules of play store and app store api
