### ISSUE TITLE
error: package com.ibits.react_native_in_app_review does not exist

### ISSUE THREAD

**Issue by cristianolopessantos** [MinaSamir11/react-native-in-app-review#76]
I tried followed steps to install manually, but i got a error. 
There is a very similar closed issue, but it was not actually resolved

file  settings.gradle
include ':react-native-in-app-review'
project(':react-native-in-app-review').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-in-app-
review/android')

file MainApplication.java
import com.ibits.react_native_in_app_review.AppReviewPackage;
..new AppReviewPackage(),

Environment: MacOs BigSur, only happens in android device

> Task :app:compileDebugJavaWithJavac FAILED
/Users/xxx/xxx/www/xxx/xxx/android/app/src/main/java/com/xxx/MainApplication.java:5: error: package com.ibits.react_native_in_app_review does not exist
import com.ibits.react_native_in_app_review.AppReviewPackage;
                                           ^
/Users/xxx/xxx/www/xxx/xxx/android/app/src/main/java/com/xxx/MainApplication.java:48: error: cannot find symbol
            new AppReviewPackage(),
                ^
  symbol: class AppReviewPackage
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by MinaSamir11** [comment]
what is you RN version ?

**Comment by MinaSamir11** [comment]
is package installed well ?
2- when you follow manual install these mean that your RN version is less than 0.60 
3- so we go through to solve these according to your project is < 0.60, does your project structure (node-modules, etc,…) has a specific nature. 
4- did you migrate to androidx and add two lines as described in manual installation ?
5- did you run react-native link !!

**Comment by cristianolopessantos** [comment]
My RN Version is 0.59.10. I followed step by step the manual install

**Comment by MinaSamir11** [comment]
@cristianolopessantos  
try again with the new version, there is an available update in v3.2.3.
