### ISSUE TITLE
buildToolsVersion causing Gradle failure

### ISSUE THREAD

**Issue by dnedrow** [MinaSamir11/react-native-in-app-review#78]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-in-app-review@3.2.2` for the project I'm working on.

I just added `react-native-in-app-review@3.2.2` to my project and immediately ran into an issue where the package attempted to use build tools 28.0.3 for the Android. This caused Gradle to fail.

The Android build tools are now automatically selected based on the compileSdkVersion, so there is really no longer any need for `buildToolsVersion safeExtGet('buildToolsVersion')`.

I figured I'd open a issue for you to consider.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-in-app-review/android/build.gradle b/node_modules/react-native-in-app-review/android/build.gradle
index 4dcb5b9..4e301f7 100755
--- a/node_modules/react-native-in-app-review/android/build.gradle
+++ b/node_modules/react-native-in-app-review/android/build.gradle
@@ -29,7 +29,6 @@ def safeExtGet(name) {
 
 android {
   compileSdkVersion safeExtGet('compileSdkVersion')
-  buildToolsVersion safeExtGet('buildToolsVersion')
 
   defaultConfig {
     minSdkVersion safeExtGet('minSdkVersion')
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by MinaSamir11** [comment]
@dnedrow 
Thank you, l appreciate your help and giving me a shout 😀
I will test it and make a change in v3.2.3

**Comment by MinaSamir11** [comment]
@EvanSays  **Sorry for late**, going to fix these issue tonight within the following hours.
