### ISSUE TITLE
hasFlowFinishedSuccessfully can return false?

### ISSUE THREAD

**Issue by gbmsimoes** [MinaSamir11/react-native-in-app-review#86]
Hi,

On `InAppReview.RequestInAppReview` will `hasFlowFinishedSuccessfully` return false if the user has already rated the app?
I'm not seeing this information explicitly anywhere... sorry if it's duplicate...

**Comment by MinaSamir11** [comment]
No problem, 

same issue here:
https://github.com/MinaSamir11/react-native-in-app-review/issues/8

You have to save date when flow launched and prompt dialog from time to time, if user rate or not and ask user to review according to guidelines for each platform avoiding limited quota issue please read doc.

https://github.com/MinaSamir11/react-native-in-app-review#system-rating-and-review-prompts
https://github.com/MinaSamir11/react-native-in-app-review#quotas

**Comment by gbmsimoes** [comment]
Ah yes! I missed that one.
Thank you for pointing it.
And thank for the reply!
