### ISSUE TITLE
Remove jcenter

### ISSUE THREAD

**Issue by AdhamMahmoud98** [MinaSamir11/react-native-in-app-review#93]
Jcenter will shutdown and it is not stable at the moment causing android builds either debug or release APKs to fail. Jcenter is used in the build.gradle file

**Comment by MinaSamir11** [comment]
yes sure, next release will solve this issue.

**Comment by swatiredhu17** [comment]
Waiting for update. Hopefully it'll be release soon. If you can provide tentative date, it would be great.

**Comment by MinaSamir11** [comment]
@swatiredhu17 
sorry for late, I will release update today.

**Comment by saczuac** [comment]
News about this ?

**Comment by MinaSamir11** [comment]
@saczuac  @swatiredhu17  package updated v3.3.2
