### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by MahyarMM** [MinaSamir11/react-native-in-app-review#94]
Hi,

Hope you are doing well. 🙂
The popup language is updated regarding the phone language.
Could it be possible to manage the popup language from the app?

**Comment by MinaSamir11** [comment]
Hello,
I'm good, i hope same to you 

No popUp managed and powered by google and apple. including ui and it's content .

**Comment by MahyarMM** [comment]
Thanks for the reply. :blush:
