### ISSUE TITLE
Upgrading to 0.67.2 with expo 44 breaks iOS build

### ISSUE THREAD

**Issue by quachdev** [MinaSamir11/react-native-in-app-review#96]
Receiving an error when trying to build iOS -- ` Duplicate interface definition for class 'RCTModuleRegistry'`

Seems related to: https://github.com/expo/expo/issues/15622

Adding `expo_patch_react_imports` does not work either. ~~It looks related to [RNInAppReviewIOS-Bridging-Header.h](https://github.com/MinaSamir11/react-native-in-app-review/blob/master/ios/RNInAppReviewIOS-Bridging-Header.h)?~~ Edit: No, downgrading to SDK 43 and back to SDK 44 seemed to run the patch properly and this does not look to be the issue.

<img width="289" alt="Screen Shot 2022-02-04 at 4 07 25 PM" src="https://user-images.githubusercontent.com/11295669/152603217-928ed776-20a4-4494-8815-b6e644d3863e.png">

**Comment by alantoa** [comment]
same issue

**Comment by lutakyn** [comment]
I'm using react native version 0.66 and it's breaking on iOS. No specific error given.

**Comment by alantoa** [comment]
@lutakyn Hi!
It is recommended that you use https://docs.expo.dev/versions/latest/sdk/storereview/

**Comment by MinaSamir11** [comment]
if you working with expo 
you have 2 option, on it is to eject your project.
- or use storereview from expo lib it self.

**Comment by MinaSamir11** [comment]
Issue resolved in V3.3.3 
Check if it's resolved yet ?

**Comment by MinaSamir11** [comment]
Issue resolved in V3.3.3 
Give me feedback, 
Thanks
