### ISSUE TITLE
How to know if the review alert was shown or not?

### ISSUE THREAD

**Issue by Arjun130995** [MinaSamir11/react-native-in-app-review#99]
I would like to track if the review alert was opened or not when calling a function InAppReview.RequestInAppReview()
Is there any way to do this.
can any one please tell me the method name i am not able to find it in 3.1.0 version

**Comment by MinaSamir11** [comment]
https://github.com/MinaSamir11/react-native-in-app-review/issues/47 
duplicated issue.
